version: '3'
services:
  activity-service: 
    build: ./RecommenderService
    container_name: recommender-service
    ports:
      - 80:80

  mysql:
    image: mysql
    container_name: mysql_recommender
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: duper
      MYSQL_DATABASE: recommender_db
    volumes:
      - ./mysql_db_data:/var/lib/mysql
      - ./entry:/docker-entrypoint-initdb.d/